name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2' 

    - name: Update Components
      run: node scripts/update-components.js

    - name: Install dependencies
      run: |
        npm install
        bundle install
      working-directory: docs-site

    - name: Build site
      run: npm run build
      working-directory: docs-site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs-site/_site
        destination_dir: _site
        publish_branch: gh-pages